name: Willka Yachay
markdown: redcarpet
highlighter: pygments
permalink: pretty
collections:
  blogposts:
    output: true
    permalink: /blog/:path/
  shopitems:
    output: true
    permalink: /shop/:path/
